permut: permut.c input_check.o algo.o
	gcc -g -ansi -pedantic -Wall permut.c input_check.c algo.c -o permut

input_checking: input_check.c input_check.h
	gcc -c -ansi -pedantic -Wall input_check.c

algo: algo.c algo.h
	gcc -c -ansi -pedantic -Wall algo.c
